### PR TITLE
Adding Gradle

### PR DESCRIPTION
**Pull request by jitpack-io**
Hi

Added Gradle and moved sources to default Gradle folders. Builds nicely.
Here is how it would look published:
https://jitpack.io/#jitpack-io/Android-DDP
and here's javadocs https://jitpack.io/com/github/jitpack-io/Android-DDP/v1.0.2/javadoc/

Happy building!

### CODE REVIEW

**Comment by mwaclawek** [comment]
Thank you!

See https://github.com/delight-im/Android-DDP/issues/48

We'll decide now if we want to publish on Jitpack, as the prerequisites are there :)

**Comment by jitpack-io** [comment]
Indeed, builds are green! https://jitpack.io/#delight-im/Android-DDP
Cheers

**Comment by mwaclawek** [comment]
@jitpack-io There are two modules in this project, `library` and `sample`. But only `library` should be packaged and published. Is this possible with your service?

https://github.com/delight-im/Android-DDP/blob/413cd62cb66c781e1e85c24dece26ce16ddeefcd/Source/library/build.gradle

**Comment by jitpack-io** [comment]
@mwaclawek Yes it's possible. Actually you don't even need to change anything as we only publish libraries by default. So in your case the sample isn't published.

**Pull request closed without merging**
